import Vue from 'vue'
import App from './App.vue'
import router from './router'
import tourneyData from './tourney-data';

Vue.config.productionTip = false

let data = {
    tourneys: tourneyData.data,
    favs: [{
        "doubles_winner_1_name": "Lukasz Kubot",
        "doubles_winner_1_player_id": "k540",
        "doubles_winner_1_player_slug": "lukasz-kubot",
        "doubles_winner_1_url": "/en/players/lukasz-kubot/k540/overview",
        "doubles_winner_2_name": "Marcelo Melo",
        "doubles_winner_2_player_id": "m919",
        "doubles_winner_2_player_slug": "marcelo-melo",
        "doubles_winner_2_url": "/en/players/marcelo-melo/m919/overview",
        "singles_winner_name": "Roger Federer",
        "singles_winner_player_id": "f324",
        "singles_winner_player_slug": "roger-federer",
        "singles_winner_url": "/en/players/roger-federer/f324/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.07.03",
        "tourney_day": 3,
        "tourney_doubles_draw": 128,
        "tourney_fin_commit": "\u00a314,840,000",
        "tourney_id": 540,
        "tourney_location": "London, Great Britain",
        "tourney_month": 7,
        "tourney_name": "Wimbledon",
        "tourney_order": 40,
        "tourney_singles_draw": 128,
        "tourney_slug": "wimbledon",
        "tourney_surface": "Grass",
        "tourney_url_suffix": "/en/scores/archive/wimbledon/540/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-540",
        "is_fav": "true"
    },
        {
            "doubles_winner_1_name": "Jean-Julien Rojer",
            "doubles_winner_1_player_id": "r513",
            "doubles_winner_1_player_slug": "jean-julien-rojer",
            "doubles_winner_1_url": "/en/players/jean-julien-rojer/r513/overview",
            "doubles_winner_2_name": "Horia Tecau",
            "doubles_winner_2_player_id": "t749",
            "doubles_winner_2_player_slug": "horia-tecau",
            "doubles_winner_2_url": "/en/players/horia-tecau/t749/overview",
            "singles_winner_name": "Rafael Nadal",
            "singles_winner_player_id": "n409",
            "singles_winner_player_slug": "rafael-nadal",
            "singles_winner_url": "/en/players/rafael-nadal/n409/overview",
            "tourney_conditions": "Outdoor",
            "tourney_dates": "2017.08.28",
            "tourney_day": 28,
            "tourney_doubles_draw": 128,
            "tourney_fin_commit": "$24,193,400",
            "tourney_id": 560,
            "tourney_location": "New York, United States",
            "tourney_month": 8,
            "tourney_name": "US Open",
            "tourney_order": 53,
            "tourney_singles_draw": 128,
            "tourney_slug": "us-open",
            "tourney_surface": "Hard",
            "tourney_url_suffix": "/en/scores/archive/us-open/560/2017/results",
            "tourney_year": 2017,
            "tourney_year_id": "2017-560",
            "is_fav": "true"
        },
        {
            "doubles_winner_1_name": "Henri Kontinen",
            "doubles_winner_1_player_id": "ka80",
            "doubles_winner_1_player_slug": "henri-kontinen",
            "doubles_winner_1_url": "/en/players/henri-kontinen/ka80/overview",
            "doubles_winner_2_name": "John Peers",
            "doubles_winner_2_player_id": "pc96",
            "doubles_winner_2_player_slug": "john-peers",
            "doubles_winner_2_url": "/en/players/john-peers/pc96/overview",
            "singles_winner_name": "Roger Federer",
            "singles_winner_player_id": "f324",
            "singles_winner_player_slug": "roger-federer",
            "singles_winner_url": "/en/players/roger-federer/f324/overview",
            "tourney_conditions": "Outdoor",
            "tourney_dates": "2017.01.16",
            "tourney_day": 16,
            "tourney_doubles_draw": 128,
            "tourney_fin_commit": "A$22,624,000",
            "tourney_id": 580,
            "tourney_location": "Melbourne, Australia",
            "tourney_month": 1,
            "tourney_name": "Australian Open",
            "tourney_order": 6,
            "tourney_singles_draw": 128,
            "tourney_slug": "australian-open",
            "tourney_surface": "Hard",
            "tourney_url_suffix": "/en/scores/archive/australian-open/580/2017/results",
            "tourney_year": 2017,
            "tourney_year_id": "2017-580",
            "is_fav": "true"
        },
        {
            "doubles_winner_1_name": "Ryan Harrison",
            "doubles_winner_1_player_id": "h940",
            "doubles_winner_1_player_slug": "ryan-harrison",
            "doubles_winner_1_url": "/en/players/ryan-harrison/h940/overview",
            "doubles_winner_2_name": "Michael Venus",
            "doubles_winner_2_player_id": "v576",
            "doubles_winner_2_player_slug": "michael-venus",
            "doubles_winner_2_url": "/en/players/michael-venus/v576/overview",
            "singles_winner_name": "Rafael Nadal",
            "singles_winner_player_id": "n409",
            "singles_winner_player_slug": "rafael-nadal",
            "singles_winner_url": "/en/players/rafael-nadal/n409/overview",
            "tourney_conditions": "Outdoor",
            "tourney_dates": "2017.05.28",
            "tourney_day": 28,
            "tourney_doubles_draw": 128,
            "tourney_fin_commit": "\u20ac16,790,000",
            "tourney_id": 520,
            "tourney_location": "Paris, France",
            "tourney_month": 5,
            "tourney_name": "Roland Garros",
            "tourney_order": 33,
            "tourney_singles_draw": 128,
            "tourney_slug": "roland-garros",
            "tourney_surface": "Clay",
            "tourney_url_suffix": "/en/scores/archive/roland-garros/520/2017/results",
            "tourney_year": 2017,
            "tourney_year_id": "2017-520",
            "is_fav": "true"
        }
    ], 
}


new Vue({
    router,
    data,
  render: h => h(App)
}).$mount('#app')
