let tourneys =
    [{
        "doubles_winner_1_name": "Thanasi Kokkinakis",
        "doubles_winner_1_player_id": "kd46",
        "doubles_winner_1_player_slug": "thanasi-kokkinakis",
        "doubles_winner_1_url": "/en/players/thanasi-kokkinakis/kd46/overview",
        "doubles_winner_2_name": "Jordan Thompson",
        "doubles_winner_2_player_id": "tc61",
        "doubles_winner_2_player_slug": "jordan-thompson",
        "doubles_winner_2_url": "/en/players/jordan-thompson/tc61/overview",
        "singles_winner_name": "Grigor Dimitrov",
        "singles_winner_player_id": "d875",
        "singles_winner_player_slug": "grigor-dimitrov",
        "singles_winner_url": "/en/players/grigor-dimitrov/d875/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.01.01",
        "tourney_day": 1,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "$495,630",
        "tourney_id": 339,
        "tourney_location": "Brisbane, Australia",
        "tourney_month": 1,
        "tourney_name": "Brisbane International presented by Suncorp",
        "tourney_order": 1,
        "tourney_singles_draw": 28,
        "tourney_slug": "brisbane",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/brisbane/339/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-339",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Rohan Bopanna",
        "doubles_winner_1_player_id": "b757",
        "doubles_winner_1_player_slug": "rohan-bopanna",
        "doubles_winner_1_url": "/en/players/rohan-bopanna/b757/overview",
        "doubles_winner_2_name": "Jeevan Nedunchezhiyan",
        "doubles_winner_2_player_id": "n480",
        "doubles_winner_2_player_slug": "jeevan-nedunchezhiyan",
        "doubles_winner_2_url": "/en/players/jeevan-nedunchezhiyan/n480/overview",
        "singles_winner_name": "Roberto Bautista Agut",
        "singles_winner_player_id": "bd06",
        "singles_winner_player_slug": "roberto-bautista-agut",
        "singles_winner_url": "/en/players/roberto-bautista-agut/bd06/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.01.02",
        "tourney_day": 2,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "$505,730",
        "tourney_id": 891,
        "tourney_location": "Chennai, India",
        "tourney_month": 1,
        "tourney_name": "Aircel Chennai Open",
        "tourney_order": 2,
        "tourney_singles_draw": 28,
        "tourney_slug": "chennai",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/chennai/891/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-891",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Jeremy Chardy",
        "doubles_winner_1_player_id": "ca12",
        "doubles_winner_1_player_slug": "jeremy-chardy",
        "doubles_winner_1_url": "/en/players/jeremy-chardy/ca12/overview",
        "doubles_winner_2_name": "Fabrice Martin",
        "doubles_winner_2_player_id": "me04",
        "doubles_winner_2_player_slug": "fabrice-martin",
        "doubles_winner_2_url": "/en/players/fabrice-martin/me04/overview",
        "singles_winner_name": "Novak Djokovic",
        "singles_winner_player_id": "d643",
        "singles_winner_player_slug": "novak-djokovic",
        "singles_winner_url": "/en/players/novak-djokovic/d643/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.01.02",
        "tourney_day": 2,
        "tourney_doubles_draw": 32,
        "tourney_fin_commit": "$1,334,270",
        "tourney_id": 451,
        "tourney_location": "Doha, Qatar",
        "tourney_month": 1,
        "tourney_name": "Qatar ExxonMobil Open",
        "tourney_order": 3,
        "tourney_singles_draw": 32,
        "tourney_slug": "doha",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/doha/451/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-451",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Wesley Koolhof",
        "doubles_winner_1_player_id": "kc41",
        "doubles_winner_1_player_slug": "wesley-koolhof",
        "doubles_winner_1_url": "/en/players/wesley-koolhof/kc41/overview",
        "doubles_winner_2_name": "Matwe Middelkoop",
        "doubles_winner_2_player_id": "mb88",
        "doubles_winner_2_player_slug": "matwe-middelkoop",
        "doubles_winner_2_url": "/en/players/matwe-middelkoop/mb88/overview",
        "singles_winner_name": "Gilles Muller",
        "singles_winner_player_id": "ma30",
        "singles_winner_player_slug": "gilles-muller",
        "singles_winner_url": "/en/players/gilles-muller/ma30/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.01.08",
        "tourney_day": 8,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "$495,630",
        "tourney_id": 338,
        "tourney_location": "Sydney, Australia",
        "tourney_month": 1,
        "tourney_name": "Sydney International",
        "tourney_order": 4,
        "tourney_singles_draw": 28,
        "tourney_slug": "sydney",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/sydney/338/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-338",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Marcin Matkowski",
        "doubles_winner_1_player_id": "m844",
        "doubles_winner_1_player_slug": "marcin-matkowski",
        "doubles_winner_1_url": "/en/players/marcin-matkowski/m844/overview",
        "doubles_winner_2_name": "Aisam-Ul-Haq Qureshi",
        "doubles_winner_2_player_id": "q019",
        "doubles_winner_2_player_slug": "aisam-ul-haq-qureshi",
        "doubles_winner_2_url": "/en/players/aisam-ul-haq-qureshi/q019/overview",
        "singles_winner_name": "Jack Sock",
        "singles_winner_player_id": "sm25",
        "singles_winner_player_slug": "jack-sock",
        "singles_winner_url": "/en/players/jack-sock/sm25/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.01.09",
        "tourney_day": 9,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "$508,360",
        "tourney_id": 301,
        "tourney_location": "Auckland, New Zealand",
        "tourney_month": 1,
        "tourney_name": "ASB Classic",
        "tourney_order": 5,
        "tourney_singles_draw": 28,
        "tourney_slug": "auckland",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/auckland/301/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-301",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Henri Kontinen",
        "doubles_winner_1_player_id": "ka80",
        "doubles_winner_1_player_slug": "henri-kontinen",
        "doubles_winner_1_url": "/en/players/henri-kontinen/ka80/overview",
        "doubles_winner_2_name": "John Peers",
        "doubles_winner_2_player_id": "pc96",
        "doubles_winner_2_player_slug": "john-peers",
        "doubles_winner_2_url": "/en/players/john-peers/pc96/overview",
        "singles_winner_name": "Roger Federer",
        "singles_winner_player_id": "f324",
        "singles_winner_player_slug": "roger-federer",
        "singles_winner_url": "/en/players/roger-federer/f324/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.01.16",
        "tourney_day": 16,
        "tourney_doubles_draw": 128,
        "tourney_fin_commit": "A$22,624,000",
        "tourney_id": 580,
        "tourney_location": "Melbourne, Australia",
        "tourney_month": 1,
        "tourney_name": "Australian Open",
        "tourney_order": 6,
        "tourney_singles_draw": 128,
        "tourney_slug": "australian-open",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/australian-open/580/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-580",
        "is_fav": "true"
    },
    {
        "doubles_winner_1_name": "Mischa Zverev",
        "doubles_winner_1_player_id": "z168",
        "doubles_winner_1_player_slug": "mischa-zverev",
        "doubles_winner_1_url": "/en/players/mischa-zverev/z168/overview",
        "doubles_winner_2_name": "Alexander Zverev",
        "doubles_winner_2_player_id": "z355",
        "doubles_winner_2_player_slug": "alexander-zverev",
        "doubles_winner_2_url": "/en/players/alexander-zverev/z355/overview",
        "singles_winner_name": "Alexander Zverev",
        "singles_winner_player_id": "z355",
        "singles_winner_player_slug": "alexander-zverev",
        "singles_winner_url": "/en/players/alexander-zverev/z355/overview",
        "tourney_conditions": "Indoor",
        "tourney_dates": "2017.02.06",
        "tourney_day": 6,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "\u20ac540,310",
        "tourney_id": 375,
        "tourney_location": "Montpellier, France",
        "tourney_month": 2,
        "tourney_name": "Open Sud de France",
        "tourney_order": 7,
        "tourney_singles_draw": 28,
        "tourney_slug": "montpellier",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/montpellier/375/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-375",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "James Cerretani",
        "doubles_winner_1_player_id": "c922",
        "doubles_winner_1_player_slug": "james-cerretani",
        "doubles_winner_1_url": "/en/players/james-cerretani/c922/overview",
        "doubles_winner_2_name": "Philipp Oswald",
        "doubles_winner_2_player_id": "o305",
        "doubles_winner_2_player_slug": "philipp-oswald",
        "doubles_winner_2_url": "/en/players/philipp-oswald/o305/overview",
        "singles_winner_name": "Victor Estrella Burgos",
        "singles_winner_player_id": "e224",
        "singles_winner_player_slug": "victor-estrella-burgos",
        "singles_winner_url": "/en/players/victor-estrella-burgos/e224/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.02.06",
        "tourney_day": 6,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "$540,310",
        "tourney_id": 7161,
        "tourney_location": "Quito, Ecuador",
        "tourney_month": 2,
        "tourney_name": "Ecuador Open",
        "tourney_order": 8,
        "tourney_singles_draw": 28,
        "tourney_slug": "quito",
        "tourney_surface": "Clay",
        "tourney_url_suffix": "/en/scores/archive/quito/7161/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-7161",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Viktor Troicki",
        "doubles_winner_1_player_id": "t840",
        "doubles_winner_1_player_slug": "viktor-troicki",
        "doubles_winner_1_url": "/en/players/viktor-troicki/t840/overview",
        "doubles_winner_2_name": "Nenad Zimonjic",
        "doubles_winner_2_player_id": "z072",
        "doubles_winner_2_player_slug": "nenad-zimonjic",
        "doubles_winner_2_url": "/en/players/nenad-zimonjic/z072/overview",
        "singles_winner_name": "Grigor Dimitrov",
        "singles_winner_player_id": "d875",
        "singles_winner_player_slug": "grigor-dimitrov",
        "singles_winner_url": "/en/players/grigor-dimitrov/d875/overview",
        "tourney_conditions": "Indoor",
        "tourney_dates": "2017.02.06",
        "tourney_day": 6,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "\u20ac540,310",
        "tourney_id": 7434,
        "tourney_location": "Sofia, Bulgaria",
        "tourney_month": 2,
        "tourney_name": "Garanti Koza Sofia Open",
        "tourney_order": 9,
        "tourney_singles_draw": 28,
        "tourney_slug": "sofia",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/sofia/7434/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-7434",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Juan Sebastian Cabal",
        "doubles_winner_1_player_id": "c834",
        "doubles_winner_1_player_slug": "juan-sebastian-cabal",
        "doubles_winner_1_url": "/en/players/juan-sebastian-cabal/c834/overview",
        "doubles_winner_2_name": "Robert Farah",
        "doubles_winner_2_player_id": "f525",
        "doubles_winner_2_player_slug": "robert-farah",
        "doubles_winner_2_url": "/en/players/robert-farah/f525/overview",
        "singles_winner_name": "Alexandr Dolgopolov",
        "singles_winner_player_id": "d801",
        "singles_winner_player_slug": "alexandr-dolgopolov",
        "singles_winner_url": "/en/players/alexandr-dolgopolov/d801/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.02.13",
        "tourney_day": 13,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "$624,340",
        "tourney_id": 506,
        "tourney_location": "Buenos Aires, Argentina",
        "tourney_month": 2,
        "tourney_name": "Argentina Open",
        "tourney_order": 10,
        "tourney_singles_draw": 28,
        "tourney_slug": "buenos-aires",
        "tourney_surface": "Clay",
        "tourney_url_suffix": "/en/scores/archive/buenos-aires/506/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-506",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Brian Baker",
        "doubles_winner_1_player_id": "ba23",
        "doubles_winner_1_player_slug": "brian-baker",
        "doubles_winner_1_url": "/en/players/brian-baker/ba23/overview",
        "doubles_winner_2_name": "Nikola Mektic",
        "doubles_winner_2_player_id": "mf09",
        "doubles_winner_2_player_slug": "nikola-mektic",
        "doubles_winner_2_url": "/en/players/nikola-mektic/mf09/overview",
        "singles_winner_name": "Ryan Harrison",
        "singles_winner_player_id": "h940",
        "singles_winner_player_slug": "ryan-harrison",
        "singles_winner_url": "/en/players/ryan-harrison/h940/overview",
        "tourney_conditions": "Indoor",
        "tourney_dates": "2017.02.13",
        "tourney_day": 13,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "$720,410",
        "tourney_id": 402,
        "tourney_location": "Memphis, United States",
        "tourney_month": 2,
        "tourney_name": "Memphis Open",
        "tourney_order": 11,
        "tourney_singles_draw": 28,
        "tourney_slug": "memphis",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/memphis/402/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-402",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Ivan Dodig",
        "doubles_winner_1_player_id": "d646",
        "doubles_winner_1_player_slug": "ivan-dodig",
        "doubles_winner_1_url": "/en/players/ivan-dodig/d646/overview",
        "doubles_winner_2_name": "Marcel Granollers",
        "doubles_winner_2_player_id": "g710",
        "doubles_winner_2_player_slug": "marcel-granollers",
        "doubles_winner_2_url": "/en/players/marcel-granollers/g710/overview",
        "singles_winner_name": "Jo-Wilfried Tsonga",
        "singles_winner_player_id": "t786",
        "singles_winner_player_slug": "jo-wilfried-tsonga",
        "singles_winner_url": "/en/players/jo-wilfried-tsonga/t786/overview",
        "tourney_conditions": "Indoor",
        "tourney_dates": "2017.02.13",
        "tourney_day": 13,
        "tourney_doubles_draw": 32,
        "tourney_fin_commit": "\u20ac1,854,365",
        "tourney_id": 407,
        "tourney_location": "Rotterdam, Netherlands",
        "tourney_month": 2,
        "tourney_name": "ABN Amro World Tennis Tournament",
        "tourney_order": 12,
        "tourney_singles_draw": 32,
        "tourney_slug": "rotterdam",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/rotterdam/407/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-407",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Raven Klaasen",
        "doubles_winner_1_player_id": "k609",
        "doubles_winner_1_player_slug": "raven-klaasen",
        "doubles_winner_1_url": "/en/players/raven-klaasen/k609/overview",
        "doubles_winner_2_name": "Rajeev Ram",
        "doubles_winner_2_player_id": "r548",
        "doubles_winner_2_player_slug": "rajeev-ram",
        "doubles_winner_2_url": "/en/players/rajeev-ram/r548/overview",
        "singles_winner_name": "Jack Sock",
        "singles_winner_player_id": "sm25",
        "singles_winner_player_slug": "jack-sock",
        "singles_winner_url": "/en/players/jack-sock/sm25/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.02.20",
        "tourney_day": 20,
        "tourney_doubles_draw": 32,
        "tourney_fin_commit": "$599,345",
        "tourney_id": 499,
        "tourney_location": "Delray Beach, United States",
        "tourney_month": 2,
        "tourney_name": "Delray Beach Open",
        "tourney_order": 13,
        "tourney_singles_draw": 32,
        "tourney_slug": "delray-beach",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/delray-beach/499/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-499",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Julien Benneteau",
        "doubles_winner_1_player_id": "b747",
        "doubles_winner_1_player_slug": "julien-benneteau",
        "doubles_winner_1_url": "/en/players/julien-benneteau/b747/overview",
        "doubles_winner_2_name": "Nicolas Mahut",
        "doubles_winner_2_player_id": "m873",
        "doubles_winner_2_player_slug": "nicolas-mahut",
        "doubles_winner_2_url": "/en/players/nicolas-mahut/m873/overview",
        "singles_winner_name": "Jo-Wilfried Tsonga",
        "singles_winner_player_id": "t786",
        "singles_winner_player_slug": "jo-wilfried-tsonga",
        "singles_winner_url": "/en/players/jo-wilfried-tsonga/t786/overview",
        "tourney_conditions": "Indoor",
        "tourney_dates": "2017.02.20",
        "tourney_day": 20,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "\u20ac691,850",
        "tourney_id": 496,
        "tourney_location": "Marseille, France",
        "tourney_month": 2,
        "tourney_name": "Open 13 Marseille",
        "tourney_order": 14,
        "tourney_singles_draw": 28,
        "tourney_slug": "marseille",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/marseille/496/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-496",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Pablo Cuevas",
        "doubles_winner_1_player_id": "c882",
        "doubles_winner_1_player_slug": "pablo-cuevas",
        "doubles_winner_1_url": "/en/players/pablo-cuevas/c882/overview",
        "doubles_winner_2_name": "Pablo Carreno Busta",
        "doubles_winner_2_player_id": "cd85",
        "doubles_winner_2_player_slug": "pablo-carreno-busta",
        "doubles_winner_2_url": "/en/players/pablo-carreno-busta/cd85/overview",
        "singles_winner_name": "Dominic Thiem",
        "singles_winner_player_id": "tb69",
        "singles_winner_player_slug": "dominic-thiem",
        "singles_winner_url": "/en/players/dominic-thiem/tb69/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.02.20",
        "tourney_day": 20,
        "tourney_doubles_draw": 32,
        "tourney_fin_commit": "$1,603,940",
        "tourney_id": 6932,
        "tourney_location": "Rio de Janeiro, Brazil",
        "tourney_month": 2,
        "tourney_name": "Rio Open presented by Claro",
        "tourney_order": 15,
        "tourney_singles_draw": 32,
        "tourney_slug": "rio-de-janeiro",
        "tourney_surface": "Clay",
        "tourney_url_suffix": "/en/scores/archive/rio-de-janeiro/6932/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-6932",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Jamie Murray",
        "doubles_winner_1_player_id": "mc81",
        "doubles_winner_1_player_slug": "jamie-murray",
        "doubles_winner_1_url": "/en/players/jamie-murray/mc81/overview",
        "doubles_winner_2_name": "Bruno Soares",
        "doubles_winner_2_player_id": "s938",
        "doubles_winner_2_player_slug": "bruno-soares",
        "doubles_winner_2_url": "/en/players/bruno-soares/s938/overview",
        "singles_winner_name": "Sam Querrey",
        "singles_winner_player_id": "q927",
        "singles_winner_player_slug": "sam-querrey",
        "singles_winner_url": "/en/players/sam-querrey/q927/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.02.27",
        "tourney_day": 27,
        "tourney_doubles_draw": 32,
        "tourney_fin_commit": "$1,633,690",
        "tourney_id": 807,
        "tourney_location": "Acapulco, Mexico",
        "tourney_month": 2,
        "tourney_name": "Abierto Mexicano Telcel",
        "tourney_order": 16,
        "tourney_singles_draw": 32,
        "tourney_slug": "acapulco",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/acapulco/807/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-807",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Jean-Julien Rojer",
        "doubles_winner_1_player_id": "r513",
        "doubles_winner_1_player_slug": "jean-julien-rojer",
        "doubles_winner_1_url": "/en/players/jean-julien-rojer/r513/overview",
        "doubles_winner_2_name": "Horia Tecau",
        "doubles_winner_2_player_id": "t749",
        "doubles_winner_2_player_slug": "horia-tecau",
        "doubles_winner_2_url": "/en/players/horia-tecau/t749/overview",
        "singles_winner_name": "Andy Murray",
        "singles_winner_player_id": "mc10",
        "singles_winner_player_slug": "andy-murray",
        "singles_winner_url": "/en/players/andy-murray/mc10/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.02.27",
        "tourney_day": 27,
        "tourney_doubles_draw": 32,
        "tourney_fin_commit": "$2,858,530",
        "tourney_id": 495,
        "tourney_location": "Dubai, United Arab Emirates",
        "tourney_month": 2,
        "tourney_name": "Dubai Duty Free Tennis Championships",
        "tourney_order": 17,
        "tourney_singles_draw": 32,
        "tourney_slug": "dubai",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/dubai/495/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-495",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Andre Sa",
        "doubles_winner_1_player_id": "s604",
        "doubles_winner_1_player_slug": "andre-sa",
        "doubles_winner_1_url": "/en/players/andre-sa/s604/overview",
        "doubles_winner_2_name": "Rogerio Dutra Silva",
        "doubles_winner_2_player_id": "sc73",
        "doubles_winner_2_player_slug": "rogerio-dutra-silva",
        "doubles_winner_2_url": "/en/players/rogerio-dutra-silva/sc73/overview",
        "singles_winner_name": "Pablo Cuevas",
        "singles_winner_player_id": "c882",
        "singles_winner_player_slug": "pablo-cuevas",
        "singles_winner_url": "/en/players/pablo-cuevas/c882/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.02.27",
        "tourney_day": 27,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "$520,285",
        "tourney_id": 533,
        "tourney_location": "Sao Paulo, Brazil",
        "tourney_month": 2,
        "tourney_name": "Brasil Open",
        "tourney_order": 18,
        "tourney_singles_draw": 28,
        "tourney_slug": "sao-paulo",
        "tourney_surface": "Clay",
        "tourney_url_suffix": "/en/scores/archive/sao-paulo/533/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-533",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Raven Klaasen",
        "doubles_winner_1_player_id": "k609",
        "doubles_winner_1_player_slug": "raven-klaasen",
        "doubles_winner_1_url": "/en/players/raven-klaasen/k609/overview",
        "doubles_winner_2_name": "Rajeev Ram",
        "doubles_winner_2_player_id": "r548",
        "doubles_winner_2_player_slug": "rajeev-ram",
        "doubles_winner_2_url": "/en/players/rajeev-ram/r548/overview",
        "singles_winner_name": "Roger Federer",
        "singles_winner_player_id": "f324",
        "singles_winner_player_slug": "roger-federer",
        "singles_winner_url": "/en/players/roger-federer/f324/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.03.09",
        "tourney_day": 9,
        "tourney_doubles_draw": 96,
        "tourney_fin_commit": "$7,913,405",
        "tourney_id": 404,
        "tourney_location": "Indian Wells, United States",
        "tourney_month": 3,
        "tourney_name": "BNP Paribas Open",
        "tourney_order": 19,
        "tourney_singles_draw": 96,
        "tourney_slug": "indian-wells",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/indian-wells/404/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-404",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Lukasz Kubot",
        "doubles_winner_1_player_id": "k540",
        "doubles_winner_1_player_slug": "lukasz-kubot",
        "doubles_winner_1_url": "/en/players/lukasz-kubot/k540/overview",
        "doubles_winner_2_name": "Marcelo Melo",
        "doubles_winner_2_player_id": "m919",
        "doubles_winner_2_player_slug": "marcelo-melo",
        "doubles_winner_2_url": "/en/players/marcelo-melo/m919/overview",
        "singles_winner_name": "Roger Federer",
        "singles_winner_player_id": "f324",
        "singles_winner_player_slug": "roger-federer",
        "singles_winner_url": "/en/players/roger-federer/f324/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.03.22",
        "tourney_day": 22,
        "tourney_doubles_draw": 96,
        "tourney_fin_commit": "$7,913,405",
        "tourney_id": 403,
        "tourney_location": "Miami, United States",
        "tourney_month": 3,
        "tourney_name": "Miami Open presented by Ita\u00fa",
        "tourney_order": 20,
        "tourney_singles_draw": 96,
        "tourney_slug": "miami",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/miami/403/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-403",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Julio Peralta",
        "doubles_winner_1_player_id": "p519",
        "doubles_winner_1_player_slug": "julio-peralta",
        "doubles_winner_1_url": "/en/players/julio-peralta/p519/overview",
        "doubles_winner_2_name": "Horacio Zeballos",
        "doubles_winner_2_player_id": "z184",
        "doubles_winner_2_player_slug": "horacio-zeballos",
        "doubles_winner_2_url": "/en/players/horacio-zeballos/z184/overview",
        "singles_winner_name": "Steve Johnson",
        "singles_winner_player_id": "j386",
        "singles_winner_player_slug": "steve-johnson",
        "singles_winner_url": "/en/players/steve-johnson/j386/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.04.10",
        "tourney_day": 10,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "$600,345",
        "tourney_id": 717,
        "tourney_location": "Houston, United States",
        "tourney_month": 4,
        "tourney_name": "Fayez Sarofim & Co. US Men\u2019s Clay Court Championship",
        "tourney_order": 21,
        "tourney_singles_draw": 28,
        "tourney_slug": "houston",
        "tourney_surface": "Clay",
        "tourney_url_suffix": "/en/scores/archive/houston/717/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-717",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Dominic Inglot",
        "doubles_winner_1_player_id": "i200",
        "doubles_winner_1_player_slug": "dominic-inglot",
        "doubles_winner_1_url": "/en/players/dominic-inglot/i200/overview",
        "doubles_winner_2_name": "Mate Pavic",
        "doubles_winner_2_player_id": "pf00",
        "doubles_winner_2_player_slug": "mate-pavic",
        "doubles_winner_2_url": "/en/players/mate-pavic/pf00/overview",
        "singles_winner_name": "Borna Coric",
        "singles_winner_player_id": "cg80",
        "singles_winner_player_slug": "borna-coric",
        "singles_winner_url": "/en/players/borna-coric/cg80/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.04.10",
        "tourney_day": 10,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "\u20ac540,310",
        "tourney_id": 360,
        "tourney_location": "Marrakech, Morocco",
        "tourney_month": 4,
        "tourney_name": "Grand Prix Hassan II",
        "tourney_order": 22,
        "tourney_singles_draw": 28,
        "tourney_slug": "marrakech",
        "tourney_surface": "Clay",
        "tourney_url_suffix": "/en/scores/archive/marrakech/360/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-360",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Rohan Bopanna",
        "doubles_winner_1_player_id": "b757",
        "doubles_winner_1_player_slug": "rohan-bopanna",
        "doubles_winner_1_url": "/en/players/rohan-bopanna/b757/overview",
        "doubles_winner_2_name": "Pablo Cuevas",
        "doubles_winner_2_player_id": "c882",
        "doubles_winner_2_player_slug": "pablo-cuevas",
        "doubles_winner_2_url": "/en/players/pablo-cuevas/c882/overview",
        "singles_winner_name": "Rafael Nadal",
        "singles_winner_player_id": "n409",
        "singles_winner_player_slug": "rafael-nadal",
        "singles_winner_url": "/en/players/rafael-nadal/n409/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.04.16",
        "tourney_day": 16,
        "tourney_doubles_draw": 56,
        "tourney_fin_commit": "\u20ac4,629,725",
        "tourney_id": 410,
        "tourney_location": "Monte Carlo, Monaco",
        "tourney_month": 4,
        "tourney_name": "Rolex Monte-Carlo Masters",
        "tourney_order": 23,
        "tourney_singles_draw": 56,
        "tourney_slug": "monte-carlo",
        "tourney_surface": "Clay",
        "tourney_url_suffix": "/en/scores/archive/monte-carlo/410/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-410",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Florin Mergea",
        "doubles_winner_1_player_id": "mb27",
        "doubles_winner_1_player_slug": "florin-mergea",
        "doubles_winner_1_url": "/en/players/florin-mergea/mb27/overview",
        "doubles_winner_2_name": "Aisam-Ul-Haq Qureshi",
        "doubles_winner_2_player_id": "q019",
        "doubles_winner_2_player_slug": "aisam-ul-haq-qureshi",
        "doubles_winner_2_url": "/en/players/aisam-ul-haq-qureshi/q019/overview",
        "singles_winner_name": "Rafael Nadal",
        "singles_winner_player_id": "n409",
        "singles_winner_player_slug": "rafael-nadal",
        "singles_winner_url": "/en/players/rafael-nadal/n409/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.04.24",
        "tourney_day": 24,
        "tourney_doubles_draw": 48,
        "tourney_fin_commit": "\u20ac2,604,340",
        "tourney_id": 425,
        "tourney_location": "Barcelona, Spain",
        "tourney_month": 4,
        "tourney_name": "Barcelona Open Banc Sabadell",
        "tourney_order": 24,
        "tourney_singles_draw": 48,
        "tourney_slug": "barcelona",
        "tourney_surface": "Clay",
        "tourney_url_suffix": "/en/scores/archive/barcelona/425/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-425",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Brian Baker",
        "doubles_winner_1_player_id": "ba23",
        "doubles_winner_1_player_slug": "brian-baker",
        "doubles_winner_1_url": "/en/players/brian-baker/ba23/overview",
        "doubles_winner_2_name": "Nikola Mektic",
        "doubles_winner_2_player_id": "mf09",
        "doubles_winner_2_player_slug": "nikola-mektic",
        "doubles_winner_2_url": "/en/players/nikola-mektic/mf09/overview",
        "singles_winner_name": "Lucas Pouille",
        "singles_winner_player_id": "pf39",
        "singles_winner_player_slug": "lucas-pouille",
        "singles_winner_url": "/en/players/lucas-pouille/pf39/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.04.24",
        "tourney_day": 24,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "\u20ac540,310",
        "tourney_id": 7648,
        "tourney_location": "Budapest, Hungary",
        "tourney_month": 4,
        "tourney_name": "Gazprom Hungarian Open",
        "tourney_order": 25,
        "tourney_singles_draw": 28,
        "tourney_slug": "budapest",
        "tourney_surface": "Clay",
        "tourney_url_suffix": "/en/scores/archive/budapest/7648/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-7648",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Ryan Harrison",
        "doubles_winner_1_player_id": "h940",
        "doubles_winner_1_player_slug": "ryan-harrison",
        "doubles_winner_1_url": "/en/players/ryan-harrison/h940/overview",
        "doubles_winner_2_name": "Michael Venus",
        "doubles_winner_2_player_id": "v576",
        "doubles_winner_2_player_slug": "michael-venus",
        "doubles_winner_2_url": "/en/players/michael-venus/v576/overview",
        "singles_winner_name": "Pablo Carreno Busta",
        "singles_winner_player_id": "cd85",
        "singles_winner_player_slug": "pablo-carreno-busta",
        "singles_winner_url": "/en/players/pablo-carreno-busta/cd85/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.05.01",
        "tourney_day": 1,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "\u20ac540,310",
        "tourney_id": 7290,
        "tourney_location": "Estoril, Portugal",
        "tourney_month": 5,
        "tourney_name": "Millennium Estoril Open",
        "tourney_order": 26,
        "tourney_singles_draw": 28,
        "tourney_slug": "estoril",
        "tourney_surface": "Clay",
        "tourney_url_suffix": "/en/scores/archive/estoril/7290/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-7290",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Roman Jebavy",
        "doubles_winner_1_player_id": "j321",
        "doubles_winner_1_player_slug": "roman-jebavy",
        "doubles_winner_1_url": "/en/players/roman-jebavy/j321/overview",
        "doubles_winner_2_name": "Jiri Vesely",
        "doubles_winner_2_player_id": "v708",
        "doubles_winner_2_player_slug": "jiri-vesely",
        "doubles_winner_2_url": "/en/players/jiri-vesely/v708/overview",
        "singles_winner_name": "Marin Cilic",
        "singles_winner_player_id": "c977",
        "singles_winner_player_slug": "marin-cilic",
        "singles_winner_url": "/en/players/marin-cilic/c977/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.05.01",
        "tourney_day": 1,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "\u20ac497,255",
        "tourney_id": 7163,
        "tourney_location": "Istanbul, Turkey",
        "tourney_month": 5,
        "tourney_name": "TEB BNP Paribas Istanbul Open",
        "tourney_order": 27,
        "tourney_singles_draw": 28,
        "tourney_slug": "istanbul",
        "tourney_surface": "Clay",
        "tourney_url_suffix": "/en/scores/archive/istanbul/7163/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-7163",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Juan Sebastian Cabal",
        "doubles_winner_1_player_id": "c834",
        "doubles_winner_1_player_slug": "juan-sebastian-cabal",
        "doubles_winner_1_url": "/en/players/juan-sebastian-cabal/c834/overview",
        "doubles_winner_2_name": "Robert Farah",
        "doubles_winner_2_player_id": "f525",
        "doubles_winner_2_player_slug": "robert-farah",
        "doubles_winner_2_url": "/en/players/robert-farah/f525/overview",
        "singles_winner_name": "Alexander Zverev",
        "singles_winner_player_id": "z355",
        "singles_winner_player_slug": "alexander-zverev",
        "singles_winner_url": "/en/players/alexander-zverev/z355/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.05.01",
        "tourney_day": 1,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "\u20ac540,310",
        "tourney_id": 308,
        "tourney_location": "Munich, Germany",
        "tourney_month": 5,
        "tourney_name": "BMW Open by FWU",
        "tourney_order": 28,
        "tourney_singles_draw": 28,
        "tourney_slug": "munich",
        "tourney_surface": "Clay",
        "tourney_url_suffix": "/en/scores/archive/munich/308/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-308",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Lukasz Kubot",
        "doubles_winner_1_player_id": "k540",
        "doubles_winner_1_player_slug": "lukasz-kubot",
        "doubles_winner_1_url": "/en/players/lukasz-kubot/k540/overview",
        "doubles_winner_2_name": "Marcelo Melo",
        "doubles_winner_2_player_id": "m919",
        "doubles_winner_2_player_slug": "marcelo-melo",
        "doubles_winner_2_url": "/en/players/marcelo-melo/m919/overview",
        "singles_winner_name": "Rafael Nadal",
        "singles_winner_player_id": "n409",
        "singles_winner_player_slug": "rafael-nadal",
        "singles_winner_url": "/en/players/rafael-nadal/n409/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.05.07",
        "tourney_day": 7,
        "tourney_doubles_draw": 56,
        "tourney_fin_commit": "\u20ac6,408,230",
        "tourney_id": 1536,
        "tourney_location": "Madrid, Spain",
        "tourney_month": 5,
        "tourney_name": "Mutua Madrid Open",
        "tourney_order": 29,
        "tourney_singles_draw": 56,
        "tourney_slug": "madrid",
        "tourney_surface": "Clay",
        "tourney_url_suffix": "/en/scores/archive/madrid/1536/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-1536",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Pierre-Hugues Herbert",
        "doubles_winner_1_player_id": "h996",
        "doubles_winner_1_player_slug": "pierre-hugues-herbert",
        "doubles_winner_1_url": "/en/players/pierre-hugues-herbert/h996/overview",
        "doubles_winner_2_name": "Nicolas Mahut",
        "doubles_winner_2_player_id": "m873",
        "doubles_winner_2_player_slug": "nicolas-mahut",
        "doubles_winner_2_url": "/en/players/nicolas-mahut/m873/overview",
        "singles_winner_name": "Alexander Zverev",
        "singles_winner_player_id": "z355",
        "singles_winner_player_slug": "alexander-zverev",
        "singles_winner_url": "/en/players/alexander-zverev/z355/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.05.14",
        "tourney_day": 14,
        "tourney_doubles_draw": 56,
        "tourney_fin_commit": "\u20ac4,835,975",
        "tourney_id": 416,
        "tourney_location": "Rome, Italy",
        "tourney_month": 5,
        "tourney_name": "Internazionali BNL d\u2019Italia",
        "tourney_order": 30,
        "tourney_singles_draw": 56,
        "tourney_slug": "rome",
        "tourney_surface": "Clay",
        "tourney_url_suffix": "/en/scores/archive/rome/416/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-416",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Jean-Julien Rojer",
        "doubles_winner_1_player_id": "r513",
        "doubles_winner_1_player_slug": "jean-julien-rojer",
        "doubles_winner_1_url": "/en/players/jean-julien-rojer/r513/overview",
        "doubles_winner_2_name": "Horia Tecau",
        "doubles_winner_2_player_id": "t749",
        "doubles_winner_2_player_slug": "horia-tecau",
        "doubles_winner_2_url": "/en/players/horia-tecau/t749/overview",
        "singles_winner_name": "Stan Wawrinka",
        "singles_winner_player_id": "w367",
        "singles_winner_player_slug": "stan-wawrinka",
        "singles_winner_url": "/en/players/stan-wawrinka/w367/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.05.21",
        "tourney_day": 21,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "\u20ac540,310",
        "tourney_id": 322,
        "tourney_location": "Geneva, Switzerland",
        "tourney_month": 5,
        "tourney_name": "Banque Eric Sturdza Geneva Open",
        "tourney_order": 31,
        "tourney_singles_draw": 28,
        "tourney_slug": "geneva",
        "tourney_surface": "Clay",
        "tourney_url_suffix": "/en/scores/archive/geneva/322/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-322",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Andres Molteni",
        "doubles_winner_1_player_id": "me56",
        "doubles_winner_1_player_slug": "andres-molteni",
        "doubles_winner_1_url": "/en/players/andres-molteni/me56/overview",
        "doubles_winner_2_name": "Adil Shamasdin",
        "doubles_winner_2_player_id": "sb92",
        "doubles_winner_2_player_slug": "adil-shamasdin",
        "doubles_winner_2_url": "/en/players/adil-shamasdin/sb92/overview",
        "singles_winner_name": "Jo-Wilfried Tsonga",
        "singles_winner_player_id": "t786",
        "singles_winner_player_slug": "jo-wilfried-tsonga",
        "singles_winner_url": "/en/players/jo-wilfried-tsonga/t786/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.05.21",
        "tourney_day": 21,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "\u20ac540,310",
        "tourney_id": 7694,
        "tourney_location": "Lyon, France",
        "tourney_month": 5,
        "tourney_name": "Open Parc Auvergne-Rh\u00f4ne-Alpes Lyon",
        "tourney_order": 32,
        "tourney_singles_draw": 28,
        "tourney_slug": "lyon",
        "tourney_surface": "Clay",
        "tourney_url_suffix": "/en/scores/archive/lyon/7694/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-7694",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Ryan Harrison",
        "doubles_winner_1_player_id": "h940",
        "doubles_winner_1_player_slug": "ryan-harrison",
        "doubles_winner_1_url": "/en/players/ryan-harrison/h940/overview",
        "doubles_winner_2_name": "Michael Venus",
        "doubles_winner_2_player_id": "v576",
        "doubles_winner_2_player_slug": "michael-venus",
        "doubles_winner_2_url": "/en/players/michael-venus/v576/overview",
        "singles_winner_name": "Rafael Nadal",
        "singles_winner_player_id": "n409",
        "singles_winner_player_slug": "rafael-nadal",
        "singles_winner_url": "/en/players/rafael-nadal/n409/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.05.28",
        "tourney_day": 28,
        "tourney_doubles_draw": 128,
        "tourney_fin_commit": "\u20ac16,790,000",
        "tourney_id": 520,
        "tourney_location": "Paris, France",
        "tourney_month": 5,
        "tourney_name": "Roland Garros",
        "tourney_order": 33,
        "tourney_singles_draw": 128,
        "tourney_slug": "roland-garros",
        "tourney_surface": "Clay",
        "tourney_url_suffix": "/en/scores/archive/roland-garros/520/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-520",
        "is_fav": "true"
    },
    {
        "doubles_winner_1_name": "Lukasz Kubot",
        "doubles_winner_1_player_id": "k540",
        "doubles_winner_1_player_slug": "lukasz-kubot",
        "doubles_winner_1_url": "/en/players/lukasz-kubot/k540/overview",
        "doubles_winner_2_name": "Marcelo Melo",
        "doubles_winner_2_player_id": "m919",
        "doubles_winner_2_player_slug": "marcelo-melo",
        "doubles_winner_2_url": "/en/players/marcelo-melo/m919/overview",
        "singles_winner_name": "Gilles Muller",
        "singles_winner_player_id": "ma30",
        "singles_winner_player_slug": "gilles-muller",
        "singles_winner_url": "/en/players/gilles-muller/ma30/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.06.12",
        "tourney_day": 12,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "\u20ac660,375",
        "tourney_id": 440,
        "tourney_location": "s-Hertogenbosch, Netherlands",
        "tourney_month": 6,
        "tourney_name": "Ricoh Open",
        "tourney_order": 34,
        "tourney_singles_draw": 28,
        "tourney_slug": "s-hertogenbosch",
        "tourney_surface": "Grass",
        "tourney_url_suffix": "/en/scores/archive/s-hertogenbosch/440/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-440",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Jamie Murray",
        "doubles_winner_1_player_id": "mc81",
        "doubles_winner_1_player_slug": "jamie-murray",
        "doubles_winner_1_url": "/en/players/jamie-murray/mc81/overview",
        "doubles_winner_2_name": "Bruno Soares",
        "doubles_winner_2_player_id": "s938",
        "doubles_winner_2_player_slug": "bruno-soares",
        "doubles_winner_2_url": "/en/players/bruno-soares/s938/overview",
        "singles_winner_name": "Lucas Pouille",
        "singles_winner_player_id": "pf39",
        "singles_winner_player_slug": "lucas-pouille",
        "singles_winner_url": "/en/players/lucas-pouille/pf39/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.06.12",
        "tourney_day": 12,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "\u20ac701,975",
        "tourney_id": 321,
        "tourney_location": "Stuttgart, Germany",
        "tourney_month": 6,
        "tourney_name": "Mercedes Cup",
        "tourney_order": 35,
        "tourney_singles_draw": 28,
        "tourney_slug": "stuttgart",
        "tourney_surface": "Grass",
        "tourney_url_suffix": "/en/scores/archive/stuttgart/321/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-321",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Lukasz Kubot",
        "doubles_winner_1_player_id": "k540",
        "doubles_winner_1_player_slug": "lukasz-kubot",
        "doubles_winner_1_url": "/en/players/lukasz-kubot/k540/overview",
        "doubles_winner_2_name": "Marcelo Melo",
        "doubles_winner_2_player_id": "m919",
        "doubles_winner_2_player_slug": "marcelo-melo",
        "doubles_winner_2_url": "/en/players/marcelo-melo/m919/overview",
        "singles_winner_name": "Roger Federer",
        "singles_winner_player_id": "f324",
        "singles_winner_player_slug": "roger-federer",
        "singles_winner_url": "/en/players/roger-federer/f324/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.06.19",
        "tourney_day": 19,
        "tourney_doubles_draw": 32,
        "tourney_fin_commit": "\u20ac1,966,095",
        "tourney_id": 500,
        "tourney_location": "Halle, Germany",
        "tourney_month": 6,
        "tourney_name": "Gerry Weber Open",
        "tourney_order": 36,
        "tourney_singles_draw": 32,
        "tourney_slug": "halle",
        "tourney_surface": "Grass",
        "tourney_url_suffix": "/en/scores/archive/halle/500/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-500",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Jamie Murray",
        "doubles_winner_1_player_id": "mc81",
        "doubles_winner_1_player_slug": "jamie-murray",
        "doubles_winner_1_url": "/en/players/jamie-murray/mc81/overview",
        "doubles_winner_2_name": "Bruno Soares",
        "doubles_winner_2_player_id": "s938",
        "doubles_winner_2_player_slug": "bruno-soares",
        "doubles_winner_2_url": "/en/players/bruno-soares/s938/overview",
        "singles_winner_name": "Feliciano Lopez",
        "singles_winner_player_id": "l397",
        "singles_winner_player_slug": "feliciano-lopez",
        "singles_winner_url": "/en/players/feliciano-lopez/l397/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.06.19",
        "tourney_day": 19,
        "tourney_doubles_draw": 32,
        "tourney_fin_commit": "\u20ac1,966,095",
        "tourney_id": 311,
        "tourney_location": "London, Great Britain",
        "tourney_month": 6,
        "tourney_name": "Aegon Championships",
        "tourney_order": 37,
        "tourney_singles_draw": 32,
        "tourney_slug": "london",
        "tourney_surface": "Grass",
        "tourney_url_suffix": "/en/scores/archive/london/311/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-311",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Robert Lindstedt",
        "doubles_winner_1_player_id": "l335",
        "doubles_winner_1_player_slug": "robert-lindstedt",
        "doubles_winner_1_url": "/en/players/robert-lindstedt/l335/overview",
        "doubles_winner_2_name": "Aisam-Ul-Haq Qureshi",
        "doubles_winner_2_player_id": "q019",
        "doubles_winner_2_player_slug": "aisam-ul-haq-qureshi",
        "doubles_winner_2_url": "/en/players/aisam-ul-haq-qureshi/q019/overview",
        "singles_winner_name": "Yuichi Sugita",
        "singles_winner_player_id": "se73",
        "singles_winner_player_slug": "yuichi-sugita",
        "singles_winner_url": "/en/players/yuichi-sugita/se73/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.06.25",
        "tourney_day": 25,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "\u20ac497,255",
        "tourney_id": 7650,
        "tourney_location": "Antalya, Turkey",
        "tourney_month": 6,
        "tourney_name": "Antalya Open",
        "tourney_order": 38,
        "tourney_singles_draw": 28,
        "tourney_slug": "antalya",
        "tourney_surface": "Grass",
        "tourney_url_suffix": "/en/scores/archive/antalya/7650/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-7650",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Bob Bryan",
        "doubles_winner_1_player_id": "b588",
        "doubles_winner_1_player_slug": "bob-bryan",
        "doubles_winner_1_url": "/en/players/bob-bryan/b588/overview",
        "doubles_winner_2_name": "Mike Bryan",
        "doubles_winner_2_player_id": "b589",
        "doubles_winner_2_player_slug": "mike-bryan",
        "doubles_winner_2_url": "/en/players/mike-bryan/b589/overview",
        "singles_winner_name": "Novak Djokovic",
        "singles_winner_player_id": "d643",
        "singles_winner_player_slug": "novak-djokovic",
        "singles_winner_url": "/en/players/novak-djokovic/d643/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.06.26",
        "tourney_day": 26,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "\u20ac693,910",
        "tourney_id": 741,
        "tourney_location": "Eastbourne, Great Britain",
        "tourney_month": 6,
        "tourney_name": "Aegon International",
        "tourney_order": 39,
        "tourney_singles_draw": 28,
        "tourney_slug": "eastbourne",
        "tourney_surface": "Grass",
        "tourney_url_suffix": "/en/scores/archive/eastbourne/741/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-741",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Lukasz Kubot",
        "doubles_winner_1_player_id": "k540",
        "doubles_winner_1_player_slug": "lukasz-kubot",
        "doubles_winner_1_url": "/en/players/lukasz-kubot/k540/overview",
        "doubles_winner_2_name": "Marcelo Melo",
        "doubles_winner_2_player_id": "m919",
        "doubles_winner_2_player_slug": "marcelo-melo",
        "doubles_winner_2_url": "/en/players/marcelo-melo/m919/overview",
        "singles_winner_name": "Roger Federer",
        "singles_winner_player_id": "f324",
        "singles_winner_player_slug": "roger-federer",
        "singles_winner_url": "/en/players/roger-federer/f324/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.07.03",
        "tourney_day": 3,
        "tourney_doubles_draw": 128,
        "tourney_fin_commit": "\u00a314,840,000",
        "tourney_id": 540,
        "tourney_location": "London, Great Britain",
        "tourney_month": 7,
        "tourney_name": "Wimbledon",
        "tourney_order": 40,
        "tourney_singles_draw": 128,
        "tourney_slug": "wimbledon",
        "tourney_surface": "Grass",
        "tourney_url_suffix": "/en/scores/archive/wimbledon/540/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-540",
        "is_fav": "true"
    },
    {
        "doubles_winner_1_name": "Julian Knowle",
        "doubles_winner_1_player_id": "k263",
        "doubles_winner_1_player_slug": "julian-knowle",
        "doubles_winner_1_url": "/en/players/julian-knowle/k263/overview",
        "doubles_winner_2_name": "Philipp Petzschner",
        "doubles_winner_2_player_id": "p624",
        "doubles_winner_2_player_slug": "philipp-petzschner",
        "doubles_winner_2_url": "/en/players/philipp-petzschner/p624/overview",
        "singles_winner_name": "David Ferrer",
        "singles_winner_player_id": "f401",
        "singles_winner_player_slug": "david-ferrer",
        "singles_winner_url": "/en/players/david-ferrer/f401/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.07.17",
        "tourney_day": 17,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "\u20ac540,310",
        "tourney_id": 316,
        "tourney_location": "Bastad, Sweden",
        "tourney_month": 7,
        "tourney_name": "SkiStar Swedish Open",
        "tourney_order": 41,
        "tourney_singles_draw": 28,
        "tourney_slug": "bastad",
        "tourney_surface": "Clay",
        "tourney_url_suffix": "/en/scores/archive/bastad/316/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-316",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Aisam-Ul-Haq Qureshi",
        "doubles_winner_1_player_id": "q019",
        "doubles_winner_1_player_slug": "aisam-ul-haq-qureshi",
        "doubles_winner_1_url": "/en/players/aisam-ul-haq-qureshi/q019/overview",
        "doubles_winner_2_name": "Rajeev Ram",
        "doubles_winner_2_player_id": "r548",
        "doubles_winner_2_player_slug": "rajeev-ram",
        "doubles_winner_2_url": "/en/players/rajeev-ram/r548/overview",
        "singles_winner_name": "John Isner",
        "singles_winner_player_id": "i186",
        "singles_winner_player_slug": "john-isner",
        "singles_winner_url": "/en/players/john-isner/i186/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.07.17",
        "tourney_day": 17,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "$600,345",
        "tourney_id": 315,
        "tourney_location": "Newport, United States",
        "tourney_month": 7,
        "tourney_name": "Dell Technologies Hall of Fame Open",
        "tourney_order": 42,
        "tourney_singles_draw": 28,
        "tourney_slug": "newport",
        "tourney_surface": "Grass",
        "tourney_url_suffix": "/en/scores/archive/newport/315/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-315",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Guillermo Duran",
        "doubles_winner_1_player_id": "d787",
        "doubles_winner_1_player_slug": "guillermo-duran",
        "doubles_winner_1_url": "/en/players/guillermo-duran/d787/overview",
        "doubles_winner_2_name": "Andres Molteni",
        "doubles_winner_2_player_id": "me56",
        "doubles_winner_2_player_slug": "andres-molteni",
        "doubles_winner_2_url": "/en/players/andres-molteni/me56/overview",
        "singles_winner_name": "Andrey Rublev",
        "singles_winner_player_id": "re44",
        "singles_winner_player_slug": "andrey-rublev",
        "singles_winner_url": "/en/players/andrey-rublev/re44/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.07.17",
        "tourney_day": 17,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "\u20ac540,310",
        "tourney_id": 439,
        "tourney_location": "Umag, Croatia",
        "tourney_month": 7,
        "tourney_name": "Plava Laguna Croatia Open Umag",
        "tourney_order": 43,
        "tourney_singles_draw": 28,
        "tourney_slug": "umag",
        "tourney_surface": "Clay",
        "tourney_url_suffix": "/en/scores/archive/umag/439/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-439",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Bob Bryan",
        "doubles_winner_1_player_id": "b588",
        "doubles_winner_1_player_slug": "bob-bryan",
        "doubles_winner_1_url": "/en/players/bob-bryan/b588/overview",
        "doubles_winner_2_name": "Mike Bryan",
        "doubles_winner_2_player_id": "b589",
        "doubles_winner_2_player_slug": "mike-bryan",
        "doubles_winner_2_url": "/en/players/mike-bryan/b589/overview",
        "singles_winner_name": "John Isner",
        "singles_winner_player_id": "i186",
        "singles_winner_player_slug": "john-isner",
        "singles_winner_url": "/en/players/john-isner/i186/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.07.24",
        "tourney_day": 24,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "$720,410",
        "tourney_id": 6116,
        "tourney_location": "Atlanta, United States",
        "tourney_month": 7,
        "tourney_name": "BB&T Atlanta Open",
        "tourney_order": 44,
        "tourney_singles_draw": 28,
        "tourney_slug": "atlanta",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/atlanta/6116/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-6116",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Oliver Marach",
        "doubles_winner_1_player_id": "m760",
        "doubles_winner_1_player_slug": "oliver-marach",
        "doubles_winner_1_url": "/en/players/oliver-marach/m760/overview",
        "doubles_winner_2_name": "Philipp Oswald",
        "doubles_winner_2_player_id": "o305",
        "doubles_winner_2_player_slug": "philipp-oswald",
        "doubles_winner_2_url": "/en/players/philipp-oswald/o305/overview",
        "singles_winner_name": "Fabio Fognini",
        "singles_winner_player_id": "f510",
        "singles_winner_player_slug": "fabio-fognini",
        "singles_winner_url": "/en/players/fabio-fognini/f510/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.07.24",
        "tourney_day": 24,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "\u20ac540,310",
        "tourney_id": 314,
        "tourney_location": "Gstaad, Switzerland",
        "tourney_month": 7,
        "tourney_name": "J. Safra Sarasin Swiss Open Gstaad",
        "tourney_order": 45,
        "tourney_singles_draw": 28,
        "tourney_slug": "gstaad",
        "tourney_surface": "Clay",
        "tourney_url_suffix": "/en/scores/archive/gstaad/314/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-314",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Ivan Dodig",
        "doubles_winner_1_player_id": "d646",
        "doubles_winner_1_player_slug": "ivan-dodig",
        "doubles_winner_1_url": "/en/players/ivan-dodig/d646/overview",
        "doubles_winner_2_name": "Mate Pavic",
        "doubles_winner_2_player_id": "pf00",
        "doubles_winner_2_player_slug": "mate-pavic",
        "doubles_winner_2_url": "/en/players/mate-pavic/pf00/overview",
        "singles_winner_name": "Leonardo Mayer",
        "singles_winner_player_id": "md56",
        "singles_winner_player_slug": "leonardo-mayer",
        "singles_winner_url": "/en/players/leonardo-mayer/md56/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.07.24",
        "tourney_day": 24,
        "tourney_doubles_draw": 32,
        "tourney_fin_commit": "\u20ac1,629,375",
        "tourney_id": 414,
        "tourney_location": "Hamburg, Germany",
        "tourney_month": 7,
        "tourney_name": "German Tennis Championships 2017",
        "tourney_order": 46,
        "tourney_singles_draw": 32,
        "tourney_slug": "hamburg",
        "tourney_surface": "Clay",
        "tourney_url_suffix": "/en/scores/archive/hamburg/414/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-414",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Pablo Cuevas",
        "doubles_winner_1_player_id": "c882",
        "doubles_winner_1_player_slug": "pablo-cuevas",
        "doubles_winner_1_url": "/en/players/pablo-cuevas/c882/overview",
        "doubles_winner_2_name": "Guillermo Duran",
        "doubles_winner_2_player_id": "d787",
        "doubles_winner_2_player_slug": "guillermo-duran",
        "doubles_winner_2_url": "/en/players/guillermo-duran/d787/overview",
        "singles_winner_name": "Philipp Kohlschreiber",
        "singles_winner_player_id": "k435",
        "singles_winner_player_slug": "philipp-kohlschreiber",
        "singles_winner_url": "/en/players/philipp-kohlschreiber/k435/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.07.31",
        "tourney_day": 31,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "\u20ac540,310",
        "tourney_id": 319,
        "tourney_location": "Kitzbuhel, Austria",
        "tourney_month": 7,
        "tourney_name": "Generali Open",
        "tourney_order": 47,
        "tourney_singles_draw": 28,
        "tourney_slug": "kitzbuhel",
        "tourney_surface": "Clay",
        "tourney_url_suffix": "/en/scores/archive/kitzbuhel/319/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-319",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Juan Sebastian Cabal",
        "doubles_winner_1_player_id": "c834",
        "doubles_winner_1_player_slug": "juan-sebastian-cabal",
        "doubles_winner_1_url": "/en/players/juan-sebastian-cabal/c834/overview",
        "doubles_winner_2_name": "Treat Huey",
        "doubles_winner_2_player_id": "h788",
        "doubles_winner_2_player_slug": "treat-huey",
        "doubles_winner_2_url": "/en/players/treat-huey/h788/overview",
        "singles_winner_name": "Sam Querrey",
        "singles_winner_player_id": "q927",
        "singles_winner_player_slug": "sam-querrey",
        "singles_winner_url": "/en/players/sam-querrey/q927/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.07.31",
        "tourney_day": 31,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "$727,995",
        "tourney_id": 7480,
        "tourney_location": "Los Cabos, Mexico",
        "tourney_month": 7,
        "tourney_name": "Abierto Mexicano de Tenis Mifel presentado por Cinemex",
        "tourney_order": 48,
        "tourney_singles_draw": 28,
        "tourney_slug": "los-cabos",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/los-cabos/7480/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-7480",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Henri Kontinen",
        "doubles_winner_1_player_id": "ka80",
        "doubles_winner_1_player_slug": "henri-kontinen",
        "doubles_winner_1_url": "/en/players/henri-kontinen/ka80/overview",
        "doubles_winner_2_name": "John Peers",
        "doubles_winner_2_player_id": "pc96",
        "doubles_winner_2_player_slug": "john-peers",
        "doubles_winner_2_url": "/en/players/john-peers/pc96/overview",
        "singles_winner_name": "Alexander Zverev",
        "singles_winner_player_id": "z355",
        "singles_winner_player_slug": "alexander-zverev",
        "singles_winner_url": "/en/players/alexander-zverev/z355/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.07.31",
        "tourney_day": 31,
        "tourney_doubles_draw": 48,
        "tourney_fin_commit": "$2,002,460",
        "tourney_id": 418,
        "tourney_location": "Washington, United States",
        "tourney_month": 7,
        "tourney_name": "Citi Open",
        "tourney_order": 49,
        "tourney_singles_draw": 48,
        "tourney_slug": "washington",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/washington/418/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-418",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Pierre-Hugues Herbert",
        "doubles_winner_1_player_id": "h996",
        "doubles_winner_1_player_slug": "pierre-hugues-herbert",
        "doubles_winner_1_url": "/en/players/pierre-hugues-herbert/h996/overview",
        "doubles_winner_2_name": "Nicolas Mahut",
        "doubles_winner_2_player_id": "m873",
        "doubles_winner_2_player_slug": "nicolas-mahut",
        "doubles_winner_2_url": "/en/players/nicolas-mahut/m873/overview",
        "singles_winner_name": "Alexander Zverev",
        "singles_winner_player_id": "z355",
        "singles_winner_player_slug": "alexander-zverev",
        "singles_winner_url": "/en/players/alexander-zverev/z355/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.08.07",
        "tourney_day": 7,
        "tourney_doubles_draw": 56,
        "tourney_fin_commit": "$5,275,595",
        "tourney_id": 421,
        "tourney_location": "Montreal, Canada",
        "tourney_month": 8,
        "tourney_name": "Coupe Rogers",
        "tourney_order": 50,
        "tourney_singles_draw": 56,
        "tourney_slug": "montreal",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/montreal/421/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-421",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Pierre-Hugues Herbert",
        "doubles_winner_1_player_id": "h996",
        "doubles_winner_1_player_slug": "pierre-hugues-herbert",
        "doubles_winner_1_url": "/en/players/pierre-hugues-herbert/h996/overview",
        "doubles_winner_2_name": "Nicolas Mahut",
        "doubles_winner_2_player_id": "m873",
        "doubles_winner_2_player_slug": "nicolas-mahut",
        "doubles_winner_2_url": "/en/players/nicolas-mahut/m873/overview",
        "singles_winner_name": "Grigor Dimitrov",
        "singles_winner_player_id": "d875",
        "singles_winner_player_slug": "grigor-dimitrov",
        "singles_winner_url": "/en/players/grigor-dimitrov/d875/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.08.13",
        "tourney_day": 13,
        "tourney_doubles_draw": 56,
        "tourney_fin_commit": "$5,627,305",
        "tourney_id": 422,
        "tourney_location": "Cincinnati, United States",
        "tourney_month": 8,
        "tourney_name": "Western & Southern Open",
        "tourney_order": 51,
        "tourney_singles_draw": 56,
        "tourney_slug": "cincinnati",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/cincinnati/422/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-422",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Jean-Julien Rojer",
        "doubles_winner_1_player_id": "r513",
        "doubles_winner_1_player_slug": "jean-julien-rojer",
        "doubles_winner_1_url": "/en/players/jean-julien-rojer/r513/overview",
        "doubles_winner_2_name": "Horia Tecau",
        "doubles_winner_2_player_id": "t749",
        "doubles_winner_2_player_slug": "horia-tecau",
        "doubles_winner_2_url": "/en/players/horia-tecau/t749/overview",
        "singles_winner_name": "Roberto Bautista Agut",
        "singles_winner_player_id": "bd06",
        "singles_winner_player_slug": "roberto-bautista-agut",
        "singles_winner_url": "/en/players/roberto-bautista-agut/bd06/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.08.20",
        "tourney_day": 20,
        "tourney_doubles_draw": 48,
        "tourney_fin_commit": "$748,960",
        "tourney_id": 6242,
        "tourney_location": "Winston-Salem, United States",
        "tourney_month": 8,
        "tourney_name": "Winston-Salem Open",
        "tourney_order": 52,
        "tourney_singles_draw": 48,
        "tourney_slug": "winston-salem",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/winston-salem/6242/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-6242",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Jean-Julien Rojer",
        "doubles_winner_1_player_id": "r513",
        "doubles_winner_1_player_slug": "jean-julien-rojer",
        "doubles_winner_1_url": "/en/players/jean-julien-rojer/r513/overview",
        "doubles_winner_2_name": "Horia Tecau",
        "doubles_winner_2_player_id": "t749",
        "doubles_winner_2_player_slug": "horia-tecau",
        "doubles_winner_2_url": "/en/players/horia-tecau/t749/overview",
        "singles_winner_name": "Rafael Nadal",
        "singles_winner_player_id": "n409",
        "singles_winner_player_slug": "rafael-nadal",
        "singles_winner_url": "/en/players/rafael-nadal/n409/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.08.28",
        "tourney_day": 28,
        "tourney_doubles_draw": 128,
        "tourney_fin_commit": "$24,193,400",
        "tourney_id": 560,
        "tourney_location": "New York, United States",
        "tourney_month": 8,
        "tourney_name": "US Open",
        "tourney_order": 53,
        "tourney_singles_draw": 128,
        "tourney_slug": "us-open",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/us-open/560/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-560",
        "is_fav": "true"
    },
    {
        "doubles_winner_1_name": "Julien Benneteau",
        "doubles_winner_1_player_id": "b747",
        "doubles_winner_1_player_slug": "julien-benneteau",
        "doubles_winner_1_url": "/en/players/julien-benneteau/b747/overview",
        "doubles_winner_2_name": "Edouard Roger-Vasselin",
        "doubles_winner_2_player_id": "r613",
        "doubles_winner_2_player_slug": "edouard-roger-vasselin",
        "doubles_winner_2_url": "/en/players/edouard-roger-vasselin/r613/overview",
        "singles_winner_name": "Peter Gojowczyk",
        "singles_winner_player_id": "g967",
        "singles_winner_player_slug": "peter-gojowczyk",
        "singles_winner_url": "/en/players/peter-gojowczyk/g967/overview",
        "tourney_conditions": "Indoor",
        "tourney_dates": "2017.09.18",
        "tourney_day": 18,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "\u20ac540,310",
        "tourney_id": 341,
        "tourney_location": "Metz, France",
        "tourney_month": 9,
        "tourney_name": "Moselle Open",
        "tourney_order": 54,
        "tourney_singles_draw": 28,
        "tourney_slug": "metz",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/metz/341/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-341",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Roman Jebavy",
        "doubles_winner_1_player_id": "j321",
        "doubles_winner_1_player_slug": "roman-jebavy",
        "doubles_winner_1_url": "/en/players/roman-jebavy/j321/overview",
        "doubles_winner_2_name": "Matwe Middelkoop",
        "doubles_winner_2_player_id": "mb88",
        "doubles_winner_2_player_slug": "matwe-middelkoop",
        "doubles_winner_2_url": "/en/players/matwe-middelkoop/mb88/overview",
        "singles_winner_name": "Damir Dzumhur",
        "singles_winner_player_id": "d923",
        "singles_winner_player_slug": "damir-dzumhur",
        "singles_winner_url": "/en/players/damir-dzumhur/d923/overview",
        "tourney_conditions": "Indoor",
        "tourney_dates": "2017.09.18",
        "tourney_day": 18,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "$1,064,715",
        "tourney_id": 568,
        "tourney_location": "St. Petersburg, Russia",
        "tourney_month": 9,
        "tourney_name": "St. Petersburg Open",
        "tourney_order": 55,
        "tourney_singles_draw": 28,
        "tourney_slug": "st-petersburg",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/st-petersburg/568/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-568",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Jonathan Erlich",
        "doubles_winner_1_player_id": "e152",
        "doubles_winner_1_player_slug": "jonathan-erlich",
        "doubles_winner_1_url": "/en/players/jonathan-erlich/e152/overview",
        "doubles_winner_2_name": "Aisam-Ul-Haq Qureshi",
        "doubles_winner_2_player_id": "q019",
        "doubles_winner_2_player_slug": "aisam-ul-haq-qureshi",
        "doubles_winner_2_url": "/en/players/aisam-ul-haq-qureshi/q019/overview",
        "singles_winner_name": "Denis Istomin",
        "singles_winner_player_id": "i165",
        "singles_winner_player_slug": "denis-istomin",
        "singles_winner_url": "/en/players/denis-istomin/i165/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.09.25",
        "tourney_day": 25,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "$1,138,910",
        "tourney_id": 7581,
        "tourney_location": "Chengdu, China",
        "tourney_month": 9,
        "tourney_name": "Chengdu Open",
        "tourney_order": 56,
        "tourney_singles_draw": 28,
        "tourney_slug": "chengdu",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/chengdu/7581/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-7581",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Alexander Peya",
        "doubles_winner_1_player_id": "p467",
        "doubles_winner_1_player_slug": "alexander-peya",
        "doubles_winner_1_url": "/en/players/alexander-peya/p467/overview",
        "doubles_winner_2_name": "Rajeev Ram",
        "doubles_winner_2_player_id": "r548",
        "doubles_winner_2_player_slug": "rajeev-ram",
        "doubles_winner_2_url": "/en/players/rajeev-ram/r548/overview",
        "singles_winner_name": "David Goffin",
        "singles_winner_player_id": "gb88",
        "singles_winner_player_slug": "david-goffin",
        "singles_winner_url": "/en/players/david-goffin/gb88/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.09.25",
        "tourney_day": 25,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "$731,680",
        "tourney_id": 6967,
        "tourney_location": "Shenzhen, China",
        "tourney_month": 9,
        "tourney_name": "Shenzhen Open",
        "tourney_order": 57,
        "tourney_singles_draw": 28,
        "tourney_slug": "shenzhen",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/shenzhen/6967/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-6967",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Henri Kontinen",
        "doubles_winner_1_player_id": "ka80",
        "doubles_winner_1_player_slug": "henri-kontinen",
        "doubles_winner_1_url": "/en/players/henri-kontinen/ka80/overview",
        "doubles_winner_2_name": "John Peers",
        "doubles_winner_2_player_id": "pc96",
        "doubles_winner_2_player_slug": "john-peers",
        "doubles_winner_2_url": "/en/players/john-peers/pc96/overview",
        "singles_winner_name": "Rafael Nadal",
        "singles_winner_player_id": "n409",
        "singles_winner_player_slug": "rafael-nadal",
        "singles_winner_url": "/en/players/rafael-nadal/n409/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.10.02",
        "tourney_day": 2,
        "tourney_doubles_draw": 32,
        "tourney_fin_commit": "$4,280,460",
        "tourney_id": 747,
        "tourney_location": "Beijing, China",
        "tourney_month": 10,
        "tourney_name": "China Open",
        "tourney_order": 58,
        "tourney_singles_draw": 32,
        "tourney_slug": "beijing",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/beijing/747/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-747",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Ben Mclachlan",
        "doubles_winner_1_player_id": "mo07",
        "doubles_winner_1_player_slug": "ben-mclachlan",
        "doubles_winner_1_url": "/en/players/ben-mclachlan/mo07/overview",
        "doubles_winner_2_name": "Yasutaka Uchiyama",
        "doubles_winner_2_player_id": "u134",
        "doubles_winner_2_player_slug": "yasutaka-uchiyama",
        "doubles_winner_2_url": "/en/players/yasutaka-uchiyama/u134/overview",
        "singles_winner_name": "David Goffin",
        "singles_winner_player_id": "gb88",
        "singles_winner_player_slug": "david-goffin",
        "singles_winner_url": "/en/players/david-goffin/gb88/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.10.02",
        "tourney_day": 2,
        "tourney_doubles_draw": 32,
        "tourney_fin_commit": "$1,706,175",
        "tourney_id": 329,
        "tourney_location": "Tokyo, Japan",
        "tourney_month": 10,
        "tourney_name": "Rakuten Japan Open Tennis Championships 2017",
        "tourney_order": 59,
        "tourney_singles_draw": 32,
        "tourney_slug": "tokyo",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/tokyo/329/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-329",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Henri Kontinen",
        "doubles_winner_1_player_id": "ka80",
        "doubles_winner_1_player_slug": "henri-kontinen",
        "doubles_winner_1_url": "/en/players/henri-kontinen/ka80/overview",
        "doubles_winner_2_name": "John Peers",
        "doubles_winner_2_player_id": "pc96",
        "doubles_winner_2_player_slug": "john-peers",
        "doubles_winner_2_url": "/en/players/john-peers/pc96/overview",
        "singles_winner_name": "Roger Federer",
        "singles_winner_player_id": "f324",
        "singles_winner_player_slug": "roger-federer",
        "singles_winner_url": "/en/players/roger-federer/f324/overview",
        "tourney_conditions": "Outdoor",
        "tourney_dates": "2017.10.08",
        "tourney_day": 8,
        "tourney_doubles_draw": 56,
        "tourney_fin_commit": "$8,092,625",
        "tourney_id": 5014,
        "tourney_location": "Shanghai, China",
        "tourney_month": 10,
        "tourney_name": "Shanghai Rolex Masters",
        "tourney_order": 60,
        "tourney_singles_draw": 56,
        "tourney_slug": "shanghai",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/shanghai/5014/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-5014",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Scott Lipsky",
        "doubles_winner_1_player_id": "l580",
        "doubles_winner_1_player_slug": "scott-lipsky",
        "doubles_winner_1_url": "/en/players/scott-lipsky/l580/overview",
        "doubles_winner_2_name": "Divij Sharan",
        "doubles_winner_2_player_id": "sd46",
        "doubles_winner_2_player_slug": "divij-sharan",
        "doubles_winner_2_url": "/en/players/divij-sharan/sd46/overview",
        "singles_winner_name": "Jo-Wilfried Tsonga",
        "singles_winner_player_id": "t786",
        "singles_winner_player_slug": "jo-wilfried-tsonga",
        "singles_winner_url": "/en/players/jo-wilfried-tsonga/t786/overview",
        "tourney_conditions": "Indoor",
        "tourney_dates": "2017.10.16",
        "tourney_day": 16,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "\u20ac660,375",
        "tourney_id": 7485,
        "tourney_location": "Antwerp, Belgium",
        "tourney_month": 10,
        "tourney_name": "European Open",
        "tourney_order": 61,
        "tourney_singles_draw": 28,
        "tourney_slug": "antwerp",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/antwerp/7485/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-7485",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Max Mirnyi",
        "doubles_winner_1_player_id": "m595",
        "doubles_winner_1_player_slug": "max-mirnyi",
        "doubles_winner_1_url": "/en/players/max-mirnyi/m595/overview",
        "doubles_winner_2_name": "Philipp Oswald",
        "doubles_winner_2_player_id": "o305",
        "doubles_winner_2_player_slug": "philipp-oswald",
        "doubles_winner_2_url": "/en/players/philipp-oswald/o305/overview",
        "singles_winner_name": "Damir Dzumhur",
        "singles_winner_player_id": "d923",
        "singles_winner_player_slug": "damir-dzumhur",
        "singles_winner_url": "/en/players/damir-dzumhur/d923/overview",
        "tourney_conditions": "Indoor",
        "tourney_dates": "2017.10.16",
        "tourney_day": 16,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "$823,600",
        "tourney_id": 438,
        "tourney_location": "Moscow, Russia",
        "tourney_month": 10,
        "tourney_name": "VTB Kremlin Cup",
        "tourney_order": 62,
        "tourney_singles_draw": 28,
        "tourney_slug": "moscow",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/moscow/438/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-438",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Oliver Marach",
        "doubles_winner_1_player_id": "m760",
        "doubles_winner_1_player_slug": "oliver-marach",
        "doubles_winner_1_url": "/en/players/oliver-marach/m760/overview",
        "doubles_winner_2_name": "Mate Pavic",
        "doubles_winner_2_player_id": "pf00",
        "doubles_winner_2_player_slug": "mate-pavic",
        "doubles_winner_2_url": "/en/players/mate-pavic/pf00/overview",
        "singles_winner_name": "Juan Martin del Potro",
        "singles_winner_player_id": "d683",
        "singles_winner_player_slug": "juan-martin-del-potro",
        "singles_winner_url": "/en/players/juan-martin-del-potro/d683/overview",
        "tourney_conditions": "Indoor",
        "tourney_dates": "2017.10.16",
        "tourney_day": 16,
        "tourney_doubles_draw": 28,
        "tourney_fin_commit": "\u20ac660,375",
        "tourney_id": 429,
        "tourney_location": "Stockholm, Sweden",
        "tourney_month": 10,
        "tourney_name": "Intrum Stockholm Open",
        "tourney_order": 63,
        "tourney_singles_draw": 28,
        "tourney_slug": "stockholm",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/stockholm/429/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-429",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Ivan Dodig",
        "doubles_winner_1_player_id": "d646",
        "doubles_winner_1_player_slug": "ivan-dodig",
        "doubles_winner_1_url": "/en/players/ivan-dodig/d646/overview",
        "doubles_winner_2_name": "Marcel Granollers",
        "doubles_winner_2_player_id": "g710",
        "doubles_winner_2_player_slug": "marcel-granollers",
        "doubles_winner_2_url": "/en/players/marcel-granollers/g710/overview",
        "singles_winner_name": "Roger Federer",
        "singles_winner_player_id": "f324",
        "singles_winner_player_slug": "roger-federer",
        "singles_winner_url": "/en/players/roger-federer/f324/overview",
        "tourney_conditions": "Indoor",
        "tourney_dates": "2017.10.23",
        "tourney_day": 23,
        "tourney_doubles_draw": 32,
        "tourney_fin_commit": "\u20ac2,291,860",
        "tourney_id": 328,
        "tourney_location": "Basel, Switzerland",
        "tourney_month": 10,
        "tourney_name": "Swiss Indoors Basel",
        "tourney_order": 64,
        "tourney_singles_draw": 32,
        "tourney_slug": "basel",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/basel/328/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-328",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Rohan Bopanna",
        "doubles_winner_1_player_id": "b757",
        "doubles_winner_1_player_slug": "rohan-bopanna",
        "doubles_winner_1_url": "/en/players/rohan-bopanna/b757/overview",
        "doubles_winner_2_name": "Pablo Cuevas",
        "doubles_winner_2_player_id": "c882",
        "doubles_winner_2_player_slug": "pablo-cuevas",
        "doubles_winner_2_url": "/en/players/pablo-cuevas/c882/overview",
        "singles_winner_name": "Lucas Pouille",
        "singles_winner_player_id": "pf39",
        "singles_winner_player_slug": "lucas-pouille",
        "singles_winner_url": "/en/players/lucas-pouille/pf39/overview",
        "tourney_conditions": "Indoor",
        "tourney_dates": "2017.10.23",
        "tourney_day": 23,
        "tourney_doubles_draw": 32,
        "tourney_fin_commit": "\u20ac2,621,850",
        "tourney_id": 337,
        "tourney_location": "Vienna, Austria",
        "tourney_month": 10,
        "tourney_name": "Erste Bank Open 500",
        "tourney_order": 65,
        "tourney_singles_draw": 32,
        "tourney_slug": "vienna",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/vienna/337/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-337",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Lukasz Kubot",
        "doubles_winner_1_player_id": "k540",
        "doubles_winner_1_player_slug": "lukasz-kubot",
        "doubles_winner_1_url": "/en/players/lukasz-kubot/k540/overview",
        "doubles_winner_2_name": "Marcelo Melo",
        "doubles_winner_2_player_id": "m919",
        "doubles_winner_2_player_slug": "marcelo-melo",
        "doubles_winner_2_url": "/en/players/marcelo-melo/m919/overview",
        "singles_winner_name": "Jack Sock",
        "singles_winner_player_id": "sm25",
        "singles_winner_player_slug": "jack-sock",
        "singles_winner_url": "/en/players/jack-sock/sm25/overview",
        "tourney_conditions": "Indoor",
        "tourney_dates": "2017.10.30",
        "tourney_day": 30,
        "tourney_doubles_draw": 48,
        "tourney_fin_commit": "\u20ac4,835,975",
        "tourney_id": 352,
        "tourney_location": "Paris, France",
        "tourney_month": 10,
        "tourney_name": "Rolex Paris Masters",
        "tourney_order": 66,
        "tourney_singles_draw": 48,
        "tourney_slug": "paris",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/paris/352/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-352",
        "is_fav": "false"
    },
    {
        "doubles_winner_1_name": "Henri Kontinen",
        "doubles_winner_1_player_id": "ka80",
        "doubles_winner_1_player_slug": "henri-kontinen",
        "doubles_winner_1_url": "/en/players/henri-kontinen/ka80/overview",
        "doubles_winner_2_name": "John Peers",
        "doubles_winner_2_player_id": "pc96",
        "doubles_winner_2_player_slug": "john-peers",
        "doubles_winner_2_url": "/en/players/john-peers/pc96/overview",
        "singles_winner_name": "Grigor Dimitrov",
        "singles_winner_player_id": "d875",
        "singles_winner_player_slug": "grigor-dimitrov",
        "singles_winner_url": "/en/players/grigor-dimitrov/d875/overview",
        "tourney_conditions": "Indoor",
        "tourney_dates": "2017.11.12",
        "tourney_day": 12,
        "tourney_doubles_draw": 8,
        "tourney_fin_commit": "$8,000,000",
        "tourney_id": 605,
        "tourney_location": "London, Great Britain",
        "tourney_month": 11,
        "tourney_name": "Nitto ATP Finals",
        "tourney_order": 67,
        "tourney_singles_draw": 8,
        "tourney_slug": "nitto-atp-finals",
        "tourney_surface": "Hard",
        "tourney_url_suffix": "/en/scores/archive/nitto-atp-finals/605/2017/results",
        "tourney_year": 2017,
        "tourney_year_id": "2017-605",
        "is_fav": "false"
    }]

export default {
    data: tourneys
};